[platformio]
default_envs = esp32-dev

[env:esp32-dev]
platform = espressif32@6.5.0
board = esp32dev
framework = arduino

upload_port = COM1    ; ← ДОБАВЬТЕ ЭТУ СТРОКУ (замените на ваш порт)
monitor_port = COM1   ; ← И ЭТУ

board_build.f_cpu = 240000000L
board_build.flash_mode = dio
board_build.flash_size = 4MB
board_build.partitions = default.csv

build_flags = 
    -O2
    -DUSER_SETUP_LOADED=1
    -DST7789_DRIVER=1
    -DTFT_WIDTH=320
    -DTFT_HEIGHT=240
    -DTFT_MOSI=23
    -DTFT_SCLK=18
    -DTFT_CS=5
    -DTFT_DC=16
    -DTFT_RST=17
    -DTFT_BL=19
    -DSPI_FREQUENCY=40000000
    -DSUPPORT_TRANSACTIONS=1

lib_deps = 
    bodmer/TFT_eSPI@^2.5.43
    bblanchon/ArduinoJson@^7.4.3
    earlephilhower/ESP8266Audio@^1.9.9

monitor_speed = 115200